app:
  id: 1 # appId
  client_id: <your_client_id>
  client_secret: <your_client_secret>
  webhook_secret: <your_webhook_secret>
  private_key: <your_private_key>
receivers:
  - url: http://example.com/webhooks
    webhook_secret: <your_webhook_secret>
  - url: http://another-example.com/webhooks
    webhook_secret: <your_webhook_secret>
